name: Pages
on:
  push:
    branches:
    - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx_copybutton
      - name: Sphinx build
        run: |
          sh update_docs.sh
      - name: Build and Commit
        uses: sphinx-notes/pages@v2
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages