name: Build and test
on:
  push:
    branches:
      - main
  pull-request:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get install -y libportaudio2 libasound-dev libsndfile1 ffmpeg
          pip install -r requirements.txt
      - name: Sphinx build
        run: |
          sh shell/update_docs.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
      - name: Test package
        run: |
          pip install tox
          tox
